--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Hebbinkpro/MagicCrates
build-by-default: true
branches:
  - main
projects:
  MagicCrates:
    path: ""
    icon: MagicCrates-icon.png
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.3
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
...
