--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Hebbinkpro/MagicCrates
build-by-default: true
branches:
- main
projects:
  MagicCrates:
    path: ""
    lint:
      phpstan: false
    icon: MagicCrates.png
...
