--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Hebbinkpro/MagicCrates
build-by-default: true
branches:
  - main
projects:
  MagicCrates:
    path: ""
    icon: MagicCrates-icon.png
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.2.1
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.3
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: 2.1.0
    lint:
      phpstan: false
...
