name: MagicCrates
description: Add crates to your server
author: Hebbinkpro
version: 3.0.0
main: Hebbinkpro\MagicCrates\MagicCrates
api: 5.0.0
softdepend:
  - Customies

permissions:
  magiccrates.cmd:
    default: op
    description: Access to the /magiccrates command
  magiccrates.cmd.create:
    default: op
    description: Access to the /magiccrates create command
  magiccrates.cmd.remove:
    default: op
    description: Access to the /magiccrates remove command
  magiccrates.cmd.key:
    default: op
    description: Access to the /magiccrates key command
  magiccrates.cmd.key.all:
    default: op
    description: Access to the /magiccrates keyall command
  magiccrates.break:
    default: false
  magiccrates.break.remove:
    default: op
    description: Permission to remove a crate by breaking it

