name: MagicCrates
description: Add crates to your server
author: Hebbinkpro
version: 1.0.0
main: Hebbinkpro\MagicCrates\Main
api: 3.14.2
mcpe-protocol: [389,390,407,408]

permissions:
  mc.cmd.*:
    default: op
    description: Access to the /mc command
    children:
      mc.cmd.create:
        default: op
        description: 	Access to the /mc create command
      mc.cmd.remove:
        default: op
        description: Access to the /mc remove command
      mc.cmd.makekey:
        default: op
        description: 	Access to the /mc makekey command
  mc.break.*:
    default: false
    children:
      mc.break.remove:
        default: op
        description: Permission to remove a crate by break it

