#delay: The delay before the item animation begins
#types: your crate types
#every type needs the following format, you can add as much as you want types, items and item enchantments
#for commands you can use the following formatting:
# - {player} for the player
# - {reward} for the reward
# - {crate} for the crate type
#The item probability is the probability to get that item from the crate
#
#   <crate_id>:
#     name: <crate_name>
#     rewards:
#       - name: <reward_name>
#         item: #The item that appears above the crate
#           [name: <item_name>]
#           id: <item_id>
#           [meta: <item_meta>]
#           [amount: <amount of the item>]
#           [lore: <custom item lore>]
#         enchantments:
#           - name: <enchantment_name>
#             level: <echantment_level>
#           - ...
#         commands: #Commands that only executes with this reward
#           - <command>
#           - ...
#         probability: <the probability to get the item>
#     commands: #Commands that always executes when opening this crate
#       - <command>
#       - ...

delay: 1

types:
  common:
    name: "§eCommon §6Crate"
    rewards:
      - name: "Diamond"
        item:
          name: "Diamond"
          id: "minecraft:diamond"
          amount: 1
          lore: "Diamond from a crate"
          enchantments:
            - name: "efficiency"
              level: 1
        commands:
          - "msg {player} be carefull with this diamond!"
        probability: 1
      - name: "Dirt"
        item:
          id: "minecraft:dirt"
          amount: 2
        commands: []
        probability: 2
    commands:
      - "say {player} won {reward} from a {crate}"
