#delay: The delay before the item animation begins
#types: your crate types
#every type needs the following format, you can add as much as you want types, items and item enchantments
#The item change is the change to get that item from the crate
#   <type>:
#     name: <the text that appears above the created crates>
#     rewards:
#       - name: <custom item name>
#         id: <item_id>
#         meta: <item_meta>
#         amount: <amount of the item>
#         lore: <custom item lore>
#         enchantments:
#           - id: <enchantment_id>
#             level: <echantment_level>
#         change: <the change to get the item>

delay: 1
types:
  common:
    name: §eCommon §6Crate
    rewards:
      - name: Diamantje
        id: 388
        meta: 0
        amount: 1
        lore: Super zeldzaam diamantje
        enchantments:
          - name: efficiency
            level: 500
        change: 1
      - name: Garbage
        id: 3
        meta: 1
        amount: 2
        lore: Pure Garbage
        change: 10